packages:
  - apps/*
  - packages/*
  - config/*
catalog:
  '@antfu/eslint-config': 3.2.0
  '@commitlint/cli': 19.3.0
  '@commitlint/config-conventional': 19.2.2
  '@commitlint/cz-commitlint': 19.2.0
  '@next/bundle-analyzer': 14.2.4
  '@svgr/webpack': 8.1.0
  '@turbo/gen': 1.12.4
  '@types/node': 20.11.24
  '@types/react': 18.3.3
  '@types/react-dom': 18.3.0
  autoprefixer: 10.4.19
  commitizen: 4.3.0
  dotenv: 16.4.5
  eslint: 9.9.1
  eslint-plugin-tailwindcss: 3.17.4
  eslint-config-neon: 0.1.62
  framer-motion: 11.3.2
  globals: 15.0.0
  husky: 9.0.11
  inquirer: 9.2.16
  lint-staged: 15.2.2
  lodash.merge: 4.6.2
  next: 14.2.5
  next-intl: 3.17.1
  next-sitemap: 4.2.3
  postcss: 8.4.38
  prettier: 3.3.3
  prettier-plugin-tailwindcss: 0.6.5
  react: 18.3.1
  react-dom: 18.3.1
  tailwind-variants: 0.2.1
  tailwindcss: 3.4.10
  turbo: 2.0.14
  typescript: 5.5.4
  typescript-eslint: 7.16.1
